services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_DOCUMENT_AUTH_URL=${VITE_DOCUMENT_AUTH_URL}
    ports:
      - "80:80"
    container_name: "antibullying-roleplay-client"
    image: "antibullying-roleplay-client:latest"
